/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentePresentacion;

import componenteEntidad.Autor;
import componenteEntidad.Editorial;
import componenteEntidad.Genero;
import componenteEntidad.Libro;
import componenteNegocio.AutorCN;
import componenteNegocio.GeneroCN;
import componenteNegocio.EditorialCN;
import componenteNegocio.LibroCN;
import funciones.Banda;
import funciones.CellRenderer;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enrique
 */
public class frmLibro extends javax.swing.JInternalFrame {
    boolean reg;
    int pmod;
    DefaultTableModel modelo = new DefaultTableModel();
    
    Autor autor;
    String idlibro, titulo, isbn, yearpublica;
    int nroejemplar, nropagina, nroedicion;
    
    /**
     * Creates new form frmLibro
     */
    public frmLibro() {
        initComponents();
        try {
            GeneroCN.getInstancia().llenar_datacombo(this.jCboGenero);
            EditorialCN.getInstancia().llenar_datacombo(this.jCboEditorial);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
        String nombreColumnas[]={"IdAutor","nombre"};
        modelo.setColumnIdentifiers(nombreColumnas);
        //Width de por cada columna
        Tabla.setGridColor(new java.awt.Color(214, 213, 208));
        Tabla.getColumnModel().getColumn(0).setPreferredWidth(10);
        Tabla.getColumnModel().getColumn(1).setPreferredWidth(300);
        //altura de filas
        Tabla.setRowHeight(24);
        //se asigna el nuevo CellRenderer a cada columna segun su contenido
        Tabla.getColumnModel().getColumn( 0 ).setCellRenderer( new CellRenderer("text center") );
        Tabla.getColumnModel().getColumn( 1 ).setCellRenderer( new CellRenderer("text") );
        
        controles(true);
        textos(false);
    }
    
   
    
    void limpiarTextos(){
        this.jTxtIdLibro.setText("");
        this.jTxtTitulo.setText("");
        this.jTxtISBN.setText("");
        this.jTxtNroEjemplar.setText("");
//        this.jCboIdDocumento.removeAllItems();
        this.jTxtNroPagina.setText("");
//        this.jTxtFecNacim.setText("");
        this.jTxtEdicion.setText("");
        this.jTxtYearPublica.setText("");
        this.jTxtIdAutor.setText("");
        this.jTxtAutor.setText("");
//        this.jCboIdTipoUsuario.removeAllItems();
    }

    void controles(boolean sw){
        this.jBtnNuevo.setEnabled(sw);
        this.jBtnGrabar.setEnabled(!sw);
        this.jBtnCancelar.setEnabled(!sw);
//        btnBuscar.setEnabled(sw);
//        btnEliminar.setEnabled(sw);
//        btnMostrar.setEnabled(sw);
        this.jBtnModificar.setEnabled(sw);
    }

    void textos(boolean sw){
        this.jTxtIdAutor.setEditable(sw);
        this.jTxtTitulo.setEditable(sw);
        this.jTxtISBN.setEditable(sw);
        this.jTxtNroEjemplar.setEditable(sw);
        this.jTxtNroPagina.setEnabled(sw);
        this.jTxtEdicion.setEditable(sw);
        this.jTxtYearPublica.setEditable(sw);
        this.jCboGenero.setEnabled(sw);
        this.jCboEditorial.setEnabled(sw);
    }
    
    public void convertiraMayusculasEnJtextfield(javax.swing.JTextField jTextfieldS, int pos) {
        String cadena = (jTextfieldS.getText()).toUpperCase();
        jTextfieldS.setText(cadena);
        jTextfieldS.setCaretPosition(pos);
    }
    
    public boolean verificaNoRepetirData(String id){
        boolean error = true;
        DefaultTableModel modeloTabla = (DefaultTableModel) Tabla.getModel();
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
//            JOptionPane.showMessageDialog(null,modeloTabla.getValueAt(i, 0) + " - " + id);
            if (modeloTabla.getValueAt(i, 0).equals(id)){
                error=false;
                break;
            }
        }
        return error;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtIdLibro = new javax.swing.JTextField();
        jTxtTitulo = new javax.swing.JTextField();
        jTxtISBN = new javax.swing.JTextField();
        jTxtNroEjemplar = new javax.swing.JTextField();
        jTxtNroPagina = new javax.swing.JTextField();
        jTxtEdicion = new javax.swing.JTextField();
        jTxtYearPublica = new javax.swing.JTextField();
        jCboGenero = new javax.swing.JComboBox();
        jCboEditorial = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTxtIdAutor = new javax.swing.JTextField();
        jTxtAutor = new javax.swing.JTextField();
        jBtnSelecAutor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jBtnAdd = new javax.swing.JButton();
        jBtnDel = new javax.swing.JButton();
        jBtnNuevo = new javax.swing.JButton();
        jBtnGrabar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnCerrar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Maestro Libro");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Codigo:");

        jLabel2.setText("Titulo:");

        jLabel3.setText("ISBN:");

        jLabel4.setText("Cantidad Ejemplares:");

        jLabel5.setText("Numero de paginas:");

        jLabel6.setText("Numero de Edicion:");

        jLabel7.setText("Fecha Publicacion:");

        jLabel8.setText("Genero:");

        jLabel9.setText("Editorial:");

        jTxtIdLibro.setEditable(false);
        jTxtIdLibro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTxtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtTituloKeyReleased(evt);
            }
        });

        jTxtNroEjemplar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jCboGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCboEditorial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle Autor(es)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(15, 128, 185))); // NOI18N

        jLabel10.setText("Autor:");

        jTxtIdAutor.setEnabled(false);

        jTxtAutor.setEnabled(false);

        jBtnSelecAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/find.png"))); // NOI18N
        jBtnSelecAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelecAutorActionPerformed(evt);
            }
        });

        Tabla.setModel(modelo);
        jScrollPane2.setViewportView(Tabla);

        jBtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/add.png"))); // NOI18N
        jBtnAdd.setText("Agregar");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/delete.png"))); // NOI18N
        jBtnDel.setText("Eliminar");
        jBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSelecAutor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSelecAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdd)
                    .addComponent(jBtnDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jBtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/document_spacing.png"))); // NOI18N
        jBtnNuevo.setText("Nuevo");
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        jBtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/disk.png"))); // NOI18N
        jBtnGrabar.setText("Grabar");
        jBtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGrabarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/cancel.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/pencil_go.png"))); // NOI18N
        jBtnModificar.setText("Modificar");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(75, 75, 75)
                                            .addComponent(jLabel2)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtNroEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNroPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtYearPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCboGenero, 0, 311, Short.MAX_VALUE)
                            .addComponent(jCboEditorial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtTitulo))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jBtnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtNroEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtNroPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTxtYearPublica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnModificar)
                    .addComponent(jBtnNuevo)
                    .addComponent(jBtnGrabar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        jBtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/door_out.png"))); // NOI18N
        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnCerrar)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        reg=true;
        textos(true);
        limpiarTextos();
        controles(false);
        try {
            this.jTxtIdLibro.setText(LibroCN.getInstancia().generaCodigo());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        this.jTxtTitulo.requestFocus();
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jBtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGrabarActionPerformed
        
        if(this.jTxtIdLibro.getText().compareTo("")!=0 && this.jTxtTitulo.getText().compareTo("")!=0) {
            try{
                idlibro=jTxtIdLibro.getText();
                titulo=jTxtTitulo.getText();
                isbn=jTxtISBN.getText();
                nroejemplar=Integer.parseInt(this.jTxtNroEjemplar.getText());
                nropagina=Integer.parseInt(this.jTxtNroPagina.getText());
                nroedicion=Integer.parseInt(this.jTxtEdicion.getText());
                yearpublica=jTxtYearPublica.getText();
                
                //Obtengo Id
                Banda banda = (Banda) this.jCboGenero.getSelectedItem();
                String id = banda.getId();
                //Lleno td
                Genero ge = GeneroCN.getInstancia().buscarGenero(id);
//                usuario.setTipoDocumento(td);
                
                //Obtengo Id2
                Banda banda2 = (Banda) this.jCboEditorial.getSelectedItem();
                String id2 = banda2.getId();
                //Lleno td
                Editorial ed = EditorialCN.getInstancia().buscarEditorial(id2);
//                usuario.setTipoDocumento(td);
                
                Libro lib=new Libro(idlibro,titulo,isbn,nroejemplar,nropagina,nroedicion,yearpublica,ge,ed);
                
                int filas = modelo.getRowCount();

                for (int i = 0; i < filas; i++){
                    String idAutor = (String) modelo.getValueAt(i, 0);
//                    JOptionPane.showMessageDialog(null, (String) modelo.getValueAt(i, 0));
                    Autor aut = AutorCN.getInstancia().buscarAutor(idAutor);
                    lib.registrarItemLibro(aut);
                }

                LibroCN.getInstancia().insertar(lib);
                JOptionPane.showMessageDialog(null, "Libro registrado");
                limpiarTextos();
                textos(false);
                controles(true);

            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jBtnGrabarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        limpiarTextos();
        textos(false);
        controles(true);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed

    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jBtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarActionPerformed

    private void jBtnSelecAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelecAutorActionPerformed
        frmSelectAutor f=new frmSelectAutor();
        f.setVisible(true);
        autor = f.autorSelec;
        this.jTxtIdAutor.setText(autor.getIdautor());
        this.jTxtAutor.setText(autor.getNombre());
    }//GEN-LAST:event_jBtnSelecAutorActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        
        if (this.jTxtIdAutor.getText().compareTo("")!=0 && this.jTxtAutor.getText().compareTo("")!=0){
            if (verificaNoRepetirData(this.jTxtIdAutor.getText())) {
                Object[] fila = {this.jTxtIdAutor.getText(), this.jTxtAutor.getText()};
                modelo.addRow(fila);
            }
            else
                JOptionPane.showMessageDialog(null, "IdAutor ya esta ingresado.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione un Autor.");
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelActionPerformed
        int i = Tabla.getSelectedRow();
        if (i != -1) {
            int rpta = JOptionPane.showConfirmDialog(null, "Esta seguro?", "Eliminar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (rpta == JOptionPane.OK_OPTION) {
                modelo.removeRow(i);
            }
        } else
            JOptionPane.showMessageDialog(null, "Seleccione un Autor", "Eliminar", 1);
    }//GEN-LAST:event_jBtnDelActionPerformed

    private void jTxtTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTituloKeyReleased
        int pos = jTxtTitulo.getCaretPosition();
        convertiraMayusculasEnJtextfield(jTxtTitulo, pos);
    }//GEN-LAST:event_jTxtTituloKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnDel;
    private javax.swing.JButton jBtnGrabar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JButton jBtnSelecAutor;
    private javax.swing.JComboBox jCboEditorial;
    private javax.swing.JComboBox jCboGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtAutor;
    private javax.swing.JTextField jTxtEdicion;
    private javax.swing.JTextField jTxtISBN;
    private javax.swing.JTextField jTxtIdAutor;
    private javax.swing.JTextField jTxtIdLibro;
    private javax.swing.JTextField jTxtNroEjemplar;
    private javax.swing.JTextField jTxtNroPagina;
    private javax.swing.JTextField jTxtTitulo;
    private javax.swing.JTextField jTxtYearPublica;
    // End of variables declaration//GEN-END:variables
}
