/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentePresentacion;

import funciones.Globales;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


/**
 *
 * @author Enrique
 */
public class frmMdi extends javax.swing.JFrame {
    
    private static frmMdi instancia;

    public static frmMdi getInstancia() {
        if(instancia==null){
            instancia = new frmMdi();
        }
        return instancia;
    }
    
    /**
     * Creates new form frmMdi
     */
    public frmMdi() {
        initComponents();
        jLblUsuario.setText(Globales.nomusu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JDesktopPane();
        jToolBar = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLblUsuario = new javax.swing.JLabel();
        jMnuBar = new javax.swing.JMenuBar();
        jMnuMaestro = new javax.swing.JMenu();
        jMnuTipoDocu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMnuGenero = new javax.swing.JMenuItem();
        jMnuEditorial = new javax.swing.JMenuItem();
        jMnuAutor = new javax.swing.JMenuItem();
        jMnuLibro = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMnuCerrar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMnuPrestamo = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnuacceso = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Biblioteca - MySQL");

        jPanel.setName(""); // NOI18N

        jToolBar.setRollover(true);

        jLabel1.setText("Usuario:   ");
        jToolBar.add(jLabel1);
        jToolBar.add(jLblUsuario);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(0, 197, Short.MAX_VALUE)
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel.setLayer(jToolBar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMnuMaestro.setText("Maestros");

        jMnuTipoDocu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/card_front.png"))); // NOI18N
        jMnuTipoDocu.setText("Tipo Documentos");
        jMnuTipoDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuTipoDocuActionPerformed(evt);
            }
        });
        jMnuMaestro.add(jMnuTipoDocu);
        jMnuMaestro.add(jSeparator1);

        jMnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/group_add.png"))); // NOI18N
        jMnuUsuario.setText("Usuarios");
        jMnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarioActionPerformed(evt);
            }
        });
        jMnuMaestro.add(jMnuUsuario);
        jMnuMaestro.add(jSeparator2);

        jMnuGenero.setText("Genero");
        jMnuGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuGeneroActionPerformed(evt);
            }
        });
        jMnuMaestro.add(jMnuGenero);

        jMnuEditorial.setText("Editorial");
        jMnuEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEditorialActionPerformed(evt);
            }
        });
        jMnuMaestro.add(jMnuEditorial);

        jMnuAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/user_suit.png"))); // NOI18N
        jMnuAutor.setText("Autor");
        jMnuAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAutorActionPerformed(evt);
            }
        });
        jMnuMaestro.add(jMnuAutor);

        jMnuLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/file_extension_thm.png"))); // NOI18N
        jMnuLibro.setText("Libro");
        jMnuLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuLibroActionPerformed(evt);
            }
        });
        jMnuMaestro.add(jMnuLibro);
        jMnuMaestro.add(jSeparator3);

        jMnuCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/door_out.png"))); // NOI18N
        jMnuCerrar.setText("Salir");
        jMnuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCerrarActionPerformed(evt);
            }
        });
        jMnuMaestro.add(jMnuCerrar);

        jMnuBar.add(jMnuMaestro);

        jMenu1.setText("Procesos");

        jMnuPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/book_add.png"))); // NOI18N
        jMnuPrestamo.setText("Prestamos");
        jMnuPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuPrestamoActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuPrestamo);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/book_go.png"))); // NOI18N
        jMenuItem2.setText("Devolucion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMnuBar.add(jMenu1);

        jMenu2.setText("Sistema");

        jMnuacceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/group_key.png"))); // NOI18N
        jMnuacceso.setText("Accesos");
        jMnuacceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuaccesoActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuacceso);
        jMenu2.add(jSeparator4);

        jMenuItem1.setText("Acerca");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMnuBar.add(jMenu2);

        setJMenuBar(jMnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuTipoDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuTipoDocuActionPerformed

        frmTipoDocu frame = new frmTipoDocu();
 
        //este metodo devuelve el tamaño de la pantalla
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        //obtenemos el tamaño de la ventana
        Dimension ventana = frame.getSize();
        //para centrar la ventana lo hacemos con el siguiente calculo
        frame.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);
        jPanel.add(frame);
        //y para finalizar la hacemos visible
        frame.setVisible(true);
        
    }//GEN-LAST:event_jMnuTipoDocuActionPerformed

    private void jMnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarioActionPerformed
        // TODO add your handling code here:
        frmUsuario usuario =  new frmUsuario();
        jPanel.add(usuario);
        usuario.setVisible(true);
    }//GEN-LAST:event_jMnuUsuarioActionPerformed

    private void jMnuGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuGeneroActionPerformed
        frmGenero genero =  new frmGenero();
        jPanel.add(genero);
        genero.setVisible(true);
    }//GEN-LAST:event_jMnuGeneroActionPerformed

    private void jMnuEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEditorialActionPerformed
        frmEditorial editorial =  new frmEditorial();
        jPanel.add(editorial);
        editorial.setVisible(true);
    }//GEN-LAST:event_jMnuEditorialActionPerformed

    private void jMnuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCerrarActionPerformed
        System.exit(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMnuCerrarActionPerformed

    private void jMnuAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAutorActionPerformed
        frmAutor autor =  new frmAutor();
        jPanel.add(autor);
        autor.setVisible(true);
    }//GEN-LAST:event_jMnuAutorActionPerformed

    private void jMnuLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLibroActionPerformed
        frmLibro libro =  new frmLibro();
        jPanel.add(libro);
        libro.setVisible(true);
    }//GEN-LAST:event_jMnuLibroActionPerformed

    private void jMnuaccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuaccesoActionPerformed
        frmAcceso acceso =  new frmAcceso();
        jPanel.add(acceso);
        acceso.setVisible(true);
    }//GEN-LAST:event_jMnuaccesoActionPerformed

    private void jMnuPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuPrestamoActionPerformed
        frmPrestamo prestamo =  new frmPrestamo();
        jPanel.add(prestamo);
        prestamo.setVisible(true);
    }//GEN-LAST:event_jMnuPrestamoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmAcerca frame = new frmAcerca();
 
        //este metodo devuelve el tamaño de la pantalla
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        //obtenemos el tamaño de la ventana
        Dimension ventana = frame.getSize();
        //para centrar la ventana lo hacemos con el siguiente calculo
        frame.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);
        jPanel.add(frame);
        //y para finalizar la hacemos visible
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null,"En construccion...");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new frmMdi().setVisible(true);
                frmMdi main = new frmMdi();
                main.setExtendedState(MAXIMIZED_BOTH);
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMnuAutor;
    private javax.swing.JMenuBar jMnuBar;
    private javax.swing.JMenuItem jMnuCerrar;
    private javax.swing.JMenuItem jMnuEditorial;
    private javax.swing.JMenuItem jMnuGenero;
    private javax.swing.JMenuItem jMnuLibro;
    private javax.swing.JMenu jMnuMaestro;
    private javax.swing.JMenuItem jMnuPrestamo;
    private javax.swing.JMenuItem jMnuTipoDocu;
    private javax.swing.JMenuItem jMnuUsuario;
    private javax.swing.JMenuItem jMnuacceso;
    private javax.swing.JDesktopPane jPanel;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
}
