/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentePresentacion;

import componenteEntidad.Libro;
import componenteEntidad.Prestamo;
import componenteEntidad.Usuario;
import componenteNegocio.LibroCN;
import componenteNegocio.PrestamoCN;
import componenteNegocio.UsuarioCN;
import funciones.CellRenderer;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enrique
 */
public class frmPrestamo extends javax.swing.JInternalFrame {
    boolean reg;
    int pmod;
    DefaultTableModel modelo = new DefaultTableModel();
    
    Usuario usuario;
    
    Libro libro;
    String idprestamo, fechamaxima;
    
    /**
     * Creates new form frmPrestamo
     */
    public frmPrestamo() {
        initComponents();
       
        String nombreColumnas[]={"IdLibro","Titulo"};
        modelo.setColumnIdentifiers(nombreColumnas);
        //Width de por cada columna
        Tabla.setGridColor(new java.awt.Color(214, 213, 208));
        Tabla.getColumnModel().getColumn(0).setPreferredWidth(10);
        Tabla.getColumnModel().getColumn(1).setPreferredWidth(300);
        //altura de filas
        Tabla.setRowHeight(24);
        //se asigna el nuevo CellRenderer a cada columna segun su contenido
        Tabla.getColumnModel().getColumn( 0 ).setCellRenderer( new CellRenderer("text center") );
        Tabla.getColumnModel().getColumn( 1 ).setCellRenderer( new CellRenderer("text") );
        
        controles(true);
        textos(false);
    }
    
    void limpiarTextos(){
        this.jTxtIdPrestamo.setText("");
        this.jTxtIdCarnet.setText("");
        this.jTxtUsuario.setText("");
        this.jTxtIdLibro.setText("");
        this.jTxtTitulo.setText("");

    }

    void controles(boolean sw)
    {
        this.jBtnNuevo.setEnabled(sw);
        this.jBtnRegistrar.setEnabled(!sw);
        this.jBtnCancelar.setEnabled(!sw);
        this.jBtnAdd.setEnabled(!sw);
        this.jBtnDel.setEnabled(!sw);
//        btnBuscar.setEnabled(sw);
//        btnEliminar.setEnabled(sw);
//        btnMostrar.setEnabled(sw);
//        this.jBtnModificar.setEnabled(sw);
    }

    void textos(boolean sw)
    {
        jBtnSelectIdCarnet.setEnabled(sw);
        jBtnSelecLibro.setEnabled(sw);
        jDtcFechaMaxima.setEnabled(sw);
        Tabla.setEnabled(sw);
    }
    
    public void convertiraMayusculasEnJtextfield(javax.swing.JTextField jTextfieldS, int pos) {
        String cadena = (jTextfieldS.getText()).toUpperCase();
        jTextfieldS.setText(cadena);
        jTextfieldS.setCaretPosition(pos);
    }
    
    public boolean verificaNoRepetirData(String id){
        boolean error = true;
        DefaultTableModel modeloTabla = (DefaultTableModel) Tabla.getModel();
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
//            JOptionPane.showMessageDialog(null,modeloTabla.getValueAt(i, 0) + " - " + id);
            if (modeloTabla.getValueAt(i, 0).equals(id)){
                error=false;
                break;
            }
        }
        return error;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtIdPrestamo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxtIdCarnet = new javax.swing.JTextField();
        jTxtUsuario = new javax.swing.JTextField();
        jBtnSelectIdCarnet = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTxtIdLibro = new javax.swing.JTextField();
        jTxtTitulo = new javax.swing.JTextField();
        jBtnSelecLibro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jBtnAdd = new javax.swing.JButton();
        jBtnDel = new javax.swing.JButton();
        jBtnCerrar = new javax.swing.JButton();
        jBtnRegistrar = new javax.swing.JButton();
        jDtcFechaMaxima = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jBtnNuevo = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setTitle("Prestamo de Libros");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nro. Prestamo:");

        jTxtIdPrestamo.setEditable(false);
        jTxtIdPrestamo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Fecha:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Datos del Usuario ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(15, 128, 185))); // NOI18N

        jLabel3.setText("Id. Carnet:");

        jTxtIdCarnet.setEditable(false);

        jTxtUsuario.setEditable(false);

        jBtnSelectIdCarnet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/find.png"))); // NOI18N
        jBtnSelectIdCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelectIdCarnetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtIdCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSelectIdCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtIdCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnSelectIdCarnet))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Detalle de Libro(s) ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(15, 128, 185))); // NOI18N

        jLabel10.setText("Libro:");

        jTxtIdLibro.setEditable(false);

        jTxtTitulo.setEditable(false);

        jBtnSelecLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/find.png"))); // NOI18N
        jBtnSelecLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelecLibroActionPerformed(evt);
            }
        });

        Tabla.setModel(modelo);
        jScrollPane2.setViewportView(Tabla);

        jBtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/add.png"))); // NOI18N
        jBtnAdd.setText("Agregar");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/delete.png"))); // NOI18N
        jBtnDel.setText("Eliminar");
        jBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtIdLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSelecLibro))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnSelecLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTxtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdd)
                    .addComponent(jBtnDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jBtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/door_out.png"))); // NOI18N
        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarActionPerformed(evt);
            }
        });

        jBtnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/accept.png"))); // NOI18N
        jBtnRegistrar.setText("Registrar Prestamo");
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha de Maxima Devolucion:");

        jBtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/document_spacing.png"))); // NOI18N
        jBtnNuevo.setText("Nuevo");
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/cancel.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(0, 290, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jBtnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCerrar)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDtcFechaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDtcFechaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRegistrar)
                    .addComponent(jBtnCerrar)
                    .addComponent(jBtnNuevo)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSelecLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelecLibroActionPerformed
        frmSelectLibro f=new frmSelectLibro();
        f.setVisible(true);
        libro = f.libroSelec;
        this.jTxtIdLibro.setText(libro.getIdlibro());
        this.jTxtTitulo.setText(libro.getTitulo());
    }//GEN-LAST:event_jBtnSelecLibroActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed

        if (this.jTxtIdLibro.getText().compareTo("")!=0 && this.jTxtTitulo.getText().compareTo("")!=0){
            if (verificaNoRepetirData(this.jTxtIdLibro.getText())) {
                Object[] fila = {this.jTxtIdLibro.getText(), this.jTxtTitulo.getText()};
                modelo.addRow(fila);
            }
            else
            JOptionPane.showMessageDialog(null, "IdLibro ya esta ingresado.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione un Libro.");
        }
        jTxtIdLibro.setText("");
        jTxtTitulo.setText("");
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelActionPerformed
        int i = Tabla.getSelectedRow();
        if (i != -1) {
            int rpta = JOptionPane.showConfirmDialog(null, "Esta seguro?", "Eliminar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (rpta == JOptionPane.OK_OPTION) {
                modelo.removeRow(i);
            }
        } else
        JOptionPane.showMessageDialog(null, "Seleccione un Autor", "Eliminar", 1);
    }//GEN-LAST:event_jBtnDelActionPerformed

    private void jBtnSelectIdCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelectIdCarnetActionPerformed
        frmSelectUsuario f=new frmSelectUsuario(); 
        f.setVisible(true);
        usuario = f.usuarioSelec;
        this.jTxtIdCarnet.setText(usuario.getIdcarnet());
        this.jTxtUsuario.setText(usuario.getApepat());
    }//GEN-LAST:event_jBtnSelectIdCarnetActionPerformed

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
        
        if(this.jTxtIdPrestamo.getText().compareTo("")!=0 && this.jDtcFechaMaxima.getDate()!=null) {
            try{
                idprestamo=jTxtIdPrestamo.getText();
                String fechamax=new SimpleDateFormat("yyyy/MM/dd").format(jDtcFechaMaxima.getDate());
                fechamaxima=fechamax;
                
                //Lleno td
                Usuario usu = UsuarioCN.getInstancia().buscarUsuario(this.jTxtIdCarnet.getText());

                Prestamo pres=new Prestamo(idprestamo,usu,fechamaxima);
                
                int filas = modelo.getRowCount();

                for (int i = 0; i < filas; i++){
                    String idlibro = (String) modelo.getValueAt(i, 0);
//                    JOptionPane.showMessageDialog(null, (String) modelo.getValueAt(i, 0));
                    Libro li = LibroCN.getInstancia().buscarLibro(idlibro);
                    pres.registrarItemPrestamo(li,"");
                }

                PrestamoCN.getInstancia().insertar(pres);
                JOptionPane.showMessageDialog(null, "Prestamo registrado");

            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        reg=true;
        textos(true);
        limpiarTextos();
        controles(false);
        try {
            this.jTxtIdPrestamo.setText(PrestamoCN.getInstancia().generaCodigo());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        this.jBtnSelectIdCarnet.requestFocus();
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jBtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        limpiarTextos();
        textos(false);
        controles(true);
    }//GEN-LAST:event_jBtnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnDel;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JButton jBtnSelecLibro;
    private javax.swing.JButton jBtnSelectIdCarnet;
    private com.toedter.calendar.JDateChooser jDtcFechaMaxima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtIdCarnet;
    private javax.swing.JTextField jTxtIdLibro;
    private javax.swing.JTextField jTxtIdPrestamo;
    private javax.swing.JTextField jTxtTitulo;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
