/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentePresentacion;
import funciones.Banda;
import componenteEntidad.TipoDocumento;
import componenteEntidad.TipoUsuario;
import componenteEntidad.Usuario;
import componenteNegocio.TipoDocumentoCN;
import componenteNegocio.TipoUsuarioCN;
import componenteNegocio.UsuarioCN;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Enrique
 */
public class frmUsuario extends javax.swing.JInternalFrame {
    boolean reg;
    int pmod;
    /**
     * Creates new form frmUsuario 
     */
    public frmUsuario() {
        initComponents();
//        setLocation(300,150);
        try {
            TipoDocumentoCN.getInstancia().llenar_datacombo(this.jCboIdDocumento);
            TipoUsuarioCN.getInstancia().llenar_datacombo(this.jCboIdTipoUsuario);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        controles(true);
        textos(false);
    }
    
    void limpiarTextos(){
        this.jTxtIdCarnet.setText("");
        this.jTxtApePat.setText("");
        this.jTxtApeMat.setText("");
        this.jTxtNombres.setText("");
//        this.jCboIdDocumento.removeAllItems();
        this.jTxtNroDocumento.setText("");
//        this.jTxtFecNacim.setText("");
        this.jTxtDireccion.setText("");
        this.jTxtTelefono.setText("");
        this.jTxtCelular.setText("");
        this.jTxtEmail.setText("");
//        this.jCboIdTipoUsuario.removeAllItems();
    }

    void controles(boolean sw)
    {
        this.jBtnNuevo.setEnabled(sw);
        this.jBtnGrabar.setEnabled(!sw);
        this.jBtnCancelar.setEnabled(!sw);
//        btnBuscar.setEnabled(sw);
//        btnEliminar.setEnabled(sw);
//        btnMostrar.setEnabled(sw);
        this.jBtnModificar.setEnabled(sw);
    }

    void textos(boolean sw)
    {
        jTxtApePat.setEditable(sw);
        jTxtApeMat.setEditable(sw);
        jTxtNombres.setEditable(sw);
        jCboIdDocumento.setEnabled(sw);
        jTxtNroDocumento.setEditable(sw);
        jTxtFecNacim.setEnabled(sw);
        jTxtDireccion.setEditable(sw);
        jTxtTelefono.setEditable(sw);
        jTxtCelular.setEditable(sw);
        jTxtEmail.setEditable(sw);
        jCboIdTipoUsuario.setEnabled(sw);
    }
    
    public void convertiraMayusculasEnJtextfield(javax.swing.JTextField jTextfieldS, int pos) {
        String cadena = (jTextfieldS.getText()).toUpperCase();
        jTextfieldS.setText(cadena);
        jTextfieldS.setCaretPosition(pos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCboIdDocumento = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtIdCarnet = new javax.swing.JTextField();
        jTxtApePat = new javax.swing.JTextField();
        jTxtApeMat = new javax.swing.JTextField();
        jTxtNombres = new javax.swing.JTextField();
        jTxtNroDocumento = new javax.swing.JTextField();
        jTxtDireccion = new javax.swing.JTextField();
        jTxtTelefono = new javax.swing.JTextField();
        jTxtCelular = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jBtnNuevo = new javax.swing.JButton();
        jBtnGrabar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jCboIdTipoUsuario = new javax.swing.JComboBox();
        jTxtFecNacim = new com.toedter.calendar.JDateChooser();
        jBtnCerrar = new javax.swing.JButton();

        setTitle("Maestro Usuarios");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Tipo documento:");

        jCboIdDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboIdDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboIdDocumentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Id. Carnet:");

        jLabel3.setText("Apellido paterno:");

        jLabel4.setText("Apellido Materno:");

        jLabel5.setText("Nombres:");

        jLabel6.setText("Nro. documento:");

        jLabel7.setText("Fecha Nacimiento:");

        jLabel8.setText("Dirección:");

        jLabel9.setText("Telefono fijo:");

        jLabel10.setText("Celular:");

        jLabel11.setText("Correo electronico:");

        jTxtIdCarnet.setEditable(false);
        jTxtIdCarnet.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTxtApePat.setBackground(new java.awt.Color(255, 255, 204));
        jTxtApePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtApePatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtApePatKeyTyped(evt);
            }
        });

        jTxtApeMat.setBackground(new java.awt.Color(255, 255, 204));
        jTxtApeMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtApeMatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtApeMatKeyTyped(evt);
            }
        });

        jTxtNombres.setBackground(new java.awt.Color(255, 255, 204));
        jTxtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtNombresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNombresKeyTyped(evt);
            }
        });

        jTxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtDireccionKeyReleased(evt);
            }
        });

        jBtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/document_spacing.png"))); // NOI18N
        jBtnNuevo.setText("Nuevo");
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        jBtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/disk.png"))); // NOI18N
        jBtnGrabar.setText("Grabar");
        jBtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGrabarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/cancel.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/pencil_go.png"))); // NOI18N
        jBtnModificar.setText("Modificar");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        jLabel12.setText("Tipo de usuario:");

        jCboIdTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtApePat)
                            .addComponent(jTxtApeMat)
                            .addComponent(jTxtEmail)
                            .addComponent(jTxtDireccion)
                            .addComponent(jCboIdDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtNombres)
                            .addComponent(jCboIdTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtNroDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jTxtCelular)
                                    .addComponent(jTxtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jTxtFecNacim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtIdCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jBtnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnGrabar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnModificar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtIdCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCboIdTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTxtApePat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCboIdDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jTxtNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jTxtFecNacim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNuevo)
                    .addComponent(jBtnGrabar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnModificar))
                .addContainerGap())
        );

        jBtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentePresentacion/png/door_out.png"))); // NOI18N
        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCerrar)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboIdDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboIdDocumentoActionPerformed
    }//GEN-LAST:event_jCboIdDocumentoActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        reg=true;
        textos(true);
        limpiarTextos();
        controles(false);
        try {
            this.jTxtIdCarnet.setText(UsuarioCN.getInstancia().generaCodigo());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        this.jTxtApePat.requestFocus();
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jBtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGrabarActionPerformed
//        String idcarnet,apepat,apemat,nombres;
        Usuario usuario = new Usuario();
        if(this.jTxtIdCarnet.getText().compareTo("")!=0 && this.jTxtApePat.getText().compareTo("")!=0 
                 && this.jTxtApeMat.getText().compareTo("")!=0  && this.jTxtNombres.getText().compareTo("")!=0) {
            try {
            usuario.setIdcarnet(this.jTxtIdCarnet.getText());
            usuario.setApepat(this.jTxtApePat.getText());
            usuario.setApemat(this.jTxtApeMat.getText());
            usuario.setNombres(this.jTxtNombres.getText());
            //Obtengo Id
            Banda banda = (Banda) this.jCboIdDocumento.getSelectedItem();
            String id = banda.getId();
            //Lleno td
            TipoDocumento td = TipoDocumentoCN.getInstancia().buscarTipoDocumento(id);
            usuario.setTipoDocumento(td);
            
            usuario.setNrodocumento(this.jTxtNroDocumento.getText());

            String fechanaci=new SimpleDateFormat("yyyy/MM/dd").format(jTxtFecNacim.getDate());
            usuario.setFechanaci(fechanaci);
            
            usuario.setDireccion(this.jTxtDireccion.getText());
            usuario.setTelefono(this.jTxtTelefono.getText());
            usuario.setCelular(this.jTxtCelular.getText());
            usuario.setEmail(this.jTxtEmail.getText());
            
            Banda banda1 = (Banda) this.jCboIdTipoUsuario.getSelectedItem();
            String idtu = banda1.getId();
            
            TipoUsuario tu = TipoUsuarioCN.getInstancia().buscarTipoUsuario(idtu);
            
            usuario.setTipoUsuario(tu);
            
            } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,"aqui " + ex.getMessage());
            }
            
            if(reg) {
                try {
                    UsuarioCN.getInstancia().insertar(usuario);
                    JOptionPane.showMessageDialog(null,"Dato registrado");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                }

            } else {
                try {
                    UsuarioCN.getInstancia().actualizar(usuario);
                    JOptionPane.showMessageDialog(null,"Dato modificado");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                }
            }
            limpiarTextos();
            textos(false);
            controles(true);
        } else
        JOptionPane.showMessageDialog(null,"faltan llenar datos");
    }//GEN-LAST:event_jBtnGrabarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        limpiarTextos();
        textos(false);
        controles(true);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        String idUsuario;
        limpiarTextos();
        idUsuario=JOptionPane.showInputDialog("IdCarnet de Usuario a Modificar : ");
        Usuario x;
        try {
            x = UsuarioCN.getInstancia().buscarUsuario(idUsuario);
            if(x!=null) {
                this.jTxtIdCarnet.setText(x.getIdcarnet());
                this.jTxtApePat.setText(x.getApepat());
                this.jTxtApeMat.setText(x.getApemat());
                this.jTxtNombres.setText(x.getNombres());
                
                this.jCboIdDocumento.setSelectedItem(x.getTipoDocumento().getDescripcion());
                this.jTxtNroDocumento.setText(x.getNrodocumento());
                
                Date fechanaci =new Date(x.getFechanaci());
                this.jTxtFecNacim.setDate(fechanaci);
                
                this.jTxtDireccion.setText(x.getDireccion());
                this.jTxtTelefono.setText(x.getTelefono());
                this.jTxtCelular.setText(x.getCelular());
                this.jTxtEmail.setText(x.getEmail());
                
                this.jCboIdTipoUsuario.setSelectedItem(x.getTipoUsuario().getDescr());
                
                reg=false;
                textos(true);
                controles(false);
            } else
            JOptionPane.showMessageDialog(null,"El IdCarnet de Usuario no existe");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jBtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarActionPerformed

    private void jTxtApePatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApePatKeyReleased
        int pos = jTxtApePat.getCaretPosition();
        convertiraMayusculasEnJtextfield(jTxtApePat, pos);
    }//GEN-LAST:event_jTxtApePatKeyReleased

    private void jTxtApeMatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApeMatKeyReleased
        int pos = jTxtApeMat.getCaretPosition();
        convertiraMayusculasEnJtextfield(jTxtApeMat, pos);
    }//GEN-LAST:event_jTxtApeMatKeyReleased

    private void jTxtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombresKeyReleased
        int pos = jTxtNombres.getCaretPosition();
        convertiraMayusculasEnJtextfield(jTxtNombres, pos);
    }//GEN-LAST:event_jTxtNombresKeyReleased

    private void jTxtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDireccionKeyReleased
        int pos = jTxtDireccion.getCaretPosition();
        convertiraMayusculasEnJtextfield(jTxtDireccion, pos);
    }//GEN-LAST:event_jTxtDireccionKeyReleased

    private void jTxtApePatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApePatKeyTyped
        char car = evt.getKeyChar();
        if(jTxtApePat.getText().length()>=45) evt.consume();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=(char)KeyEvent.VK_SPACE)){
           evt.consume();
        }
    }//GEN-LAST:event_jTxtApePatKeyTyped

    private void jTxtApeMatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApeMatKeyTyped
        char car = evt.getKeyChar();
        if(jTxtApeMat.getText().length()>=45) evt.consume();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=(char)KeyEvent.VK_SPACE)){
           evt.consume();
        }
    }//GEN-LAST:event_jTxtApeMatKeyTyped

    private void jTxtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombresKeyTyped
        char car = evt.getKeyChar();
        if(jTxtNombres.getText().length()>=45) evt.consume();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=(char)KeyEvent.VK_SPACE)){
           evt.consume();
        }
    }//GEN-LAST:event_jTxtNombresKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnGrabar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JComboBox jCboIdDocumento;
    private javax.swing.JComboBox jCboIdTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtApeMat;
    private javax.swing.JTextField jTxtApePat;
    private javax.swing.JTextField jTxtCelular;
    private javax.swing.JTextField jTxtDireccion;
    private javax.swing.JTextField jTxtEmail;
    private com.toedter.calendar.JDateChooser jTxtFecNacim;
    private javax.swing.JTextField jTxtIdCarnet;
    private javax.swing.JTextField jTxtNombres;
    private javax.swing.JTextField jTxtNroDocumento;
    private javax.swing.JTextField jTxtTelefono;
    // End of variables declaration//GEN-END:variables
}
